- name: "Adding Jupyterhub repository to Helm3"
  shell: |
    microk8s helm3 repo add \ 
    jupyterhub https://jupyterhub.github.io/helm-chart/
  become_user: insightlab

- name: "Updating local Helm3 repo"
  shell: microk8s helm3 repo update
  become_user: insightlab

- name: "Creating the namespace to Jupyterhub"
  shell: microk8s kubectl create namespace jhub
  become_user: insightlab