- name: "Update Repository cache"
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: "Upgrade Repository cache"
  become: true
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 3600
